In [10]:
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
from matplotlib import style
style.use('ggplot')
import csv 
from statistics import mean 
import glob2 
from sklearn.cluster import KMeans
manufacturers = [] 
new_list = []
with open('car_list.csv', 'rt') as f:
    reader = csv.reader(f)
    for row in reader:
        manufacturers.append(row[0])
manufacturers  = manufacturers[1:]
manufacturers_len = len(set(manufacturers))
print(manufacturers_len)
set_manunfacturers = set(manufacturers)
set_manunfacturers
import pandas as pd
import statsmodels.formula.api as sm


18


In [11]:
cars  = []
with open('car_list.csv', 'rt') as f:
    reader = csv.reader(f)
    for row in reader:
        cars.append(row[1])
cars = cars[1:]
import re
count = 0
new_list = []

for m in set_manunfacturers:
    for car in cars:
        if str(m) in str(car):
            count = count+1
            small_list = []
            new_list.append((re.sub(str(m),"",str(car),count=1)).lower())
car_list = []
print('len cars' + str(len(car_list)))

for list in new_list:
    car_list.append((' '.join(list.split(' ')[1:-1])).capitalize())
path = '/home/saksham/Desktop/majorproject/out1multipleregression/*.csv'       
print(path)
outfile = open('finalfile.csv', 'w')
writer = csv.writer(outfile)
writer.writerow(['MANUFACTURERE', 'CAR', 'a', 'b'])
print('len cars' + str(len(car_list)))
new_car_list = []

len cars0
/home/saksham/Desktop/majorproject/out1multipleregression/*.csv
len cars118


In [12]:
for file in glob2.glob(path):
    print(file)
    for car in car_list:
        
        with open(file, 'rt') as f:
           # x is year
            x = []
            # y is price
            y = []
            # z is kms
            z = []
            reader = csv.reader(f)
            for row in reader:
                if row[1].lower() == car.lower():
                    if car.lower() not  in new_car_list:
                        new_car_list.append(car.lower())
                    c = car
                    x.append((2017-int(row[3]))*10000000)
                    y.append(int(row[2]))
            
            if len(x)>0:
                man = str(file).split('/')[-1]
                print(man)
                man1 = man.split('.')[0]
                print('running')
                nparray = np.empty(shape=[0, 2])
                xs = np.empty(shape=[0,1], dtype=np.float64)
                ys = np.empty(shape=[0,1], dtype=np.float64)
                no_of_clusters = len(set(x))
                for (a, b) in zip(x,y):
                    nparray = np.append(nparray, [[a,b]], axis=0)
                
                kmeans = KMeans(n_clusters=no_of_clusters)
                kmeans.fit(nparray)
                centroids = kmeans.cluster_centers_
                labels = kmeans.labels_
                if no_of_clusters == 8:
                    colors = ["g.", "r.","c.","b.","y.", "w.", "k.", "m."]
                elif no_of_clusters == 7:
                    colors = ["g.", "r.","c.","b.","y.", "w.", "k."]
                elif  no_of_clusters == 6:
                    colors = ["g.", "r.","c.","b.","y.", "w."]
                elif no_of_clusters == 5:
                    colors = ["g.", "r.","c.","b.","y."]
                elif no_of_clusters == 4:
                    colors = ["g.", "r.","c.","b."]
                elif no_of_clusters == 3:
                    colors = ["g.", "r.","c."]
                elif no_of_clusters == 2:
                    colors = ["g.", "r."]
                elif no_of_clusters == 1:
                    colors = ["g."]
                for i in range(len(nparray)):
                    plt.plot(nparray[i][0], nparray[i][1], colors[labels[i]], markersize=10)
                plt.scatter(centroids[:, 0], centroids[:, 1], marker="x", s=150, linewidths=5, zorder=10)
                plt.xlabel("Year")
                plt.ylabel("Price")
                fig1 = plt.gcf()
                plt.draw()
                fig1.savefig('clusteredimage/' + str(car) + '.png')
                plt.close()
                ym = centroids[:,1]
                
                xm = centroids[:,0]
                for i in xm:
                    i = i/10000000
                    xs = np.append(xs, [[i]])

                for j in ym:
                    ys = np.append(ys, [[j]]) 
                # solve for a and b
                def best_fit(X, Y):

                    xbar = sum(X)/len(X)
                    ybar = sum(Y)/len(Y)
                    n = len(X) # or len(Y)

                    numer = sum(xi*yi for xi,yi in zip(X, Y)) - n * xbar * ybar
                    denum = sum(xi**2 for xi in X) - n * xbar**2

                    b = numer / denum
                    a = ybar - b * xbar

                    print('best fit line:\ny = {:.2f} +  {:.2f}x'.format(a, b))

                    return a, b

                # solution
                a, b = best_fit(xs, ys)
                print('for ' + str(car))
                
                print(a, b)
                print('before plot ')
                print(xs, ys)
                plt.scatter(xs, ys)
                yfit = [a + b * xi for xi in xs]
                plt.plot(xs, yfit)
                plt.xlabel("Year")
                plt.ylabel("Price")
                plt.grid()
                fig1 = plt.gcf()
                plt.draw()
                fig1.savefig('bestfitimage/' + str(car) + '.png')
                plt.close() 
                
#                 plt.grid()
#                 fig1 = plt.gcf()
#                 plt.draw()
                
#                 fig1.savefig('bestfitimage/' + str(car) + '.png')
                outfile = open('finalfile.csv', 'a')
                writer = csv.writer(outfile)
                writer.writerow([man1,car,a,b])

/home/saksham/Desktop/majorproject/out1multipleregression/BMW.csv
BMW.csv
running
best fit line:
y = 3104379.01 +  -230564.17x
for X1
3104379.00794 -230564.173611
before plot 
[ 7.  4.  2.  5.  6.  3.  1.] [ 2199000.          1936375.          2400000.          1606759.25
  1407721.94444444  2250000.          3475000.        ]
BMW.csv
running
best fit line:
y = 2350000.00 +  -95000.00x
for 1 series
2350000.0 -95000.0
before plot 
[ 4.  2.] [ 1970000.  2160000.]
BMW.csv
running
best fit line:
y = 4248673.72 +  -449611.39x
for 3 series
4248673.72004 -449611.394558
before plot 
[ 5.  2.  7.  4.  6.  3.  1.] [ 1815000.          3429166.66666667  1282238.09523809  2537692.23076923
  1435000.          2847500.          3805000.        ]
BMW.csv
running
best fit line:
y = 5115000.00 +  -470357.14x
for X3
5115000.0 -470357.142857
before plot 
[ 5.  1.  4.  2.  3.  6.] [ 2762500.  4700000.  2950000.  4400000.  3500000.  2500000.]
BMW.csv
running
best fit line:
y = 5107759.75 +  -440689.41x
for 

/usr/local/lib/python3.5/dist-packages/ipykernel/__main__.py:81: RuntimeWarning: invalid value encountered in double_scalars


best fit line:
y = nan +  nanx
for X6
nan nan
before plot 
[ 6.] [ 4250000.]
/home/saksham/Desktop/majorproject/out1multipleregression/Renault.csv
Renault.csv
running
best fit line:
y = 396166.67 +  -5166.67x
for Kwid
396166.666667 -5166.66666667
before plot 
[ 1.  2.] [ 391000.          385833.33333333]
Renault.csv
running
best fit line:
y = 809524.05 +  -86309.62x
for Pulse
809524.047619 -86309.6190476
before plot 
[ 5.  2.  4.] [ 354166.33333333  625000.          500000.        ]
Renault.csv
running
best fit line:
y = 627800.00 +  -2007.14x
for Scala
627800.0 -2007.14285714
before plot 
[ 5.  3.  4.  6.] [ 582500.          655000.          587571.42857143  650000.        ]
Renault.csv
running
best fit line:
y = 1011666.67 +  23333.33x
for Lodgy
1011666.66667 23333.3333333
before plot 
[ 2.  1.] [ 1058333.33333333  1035000.        ]
Renault.csv
running
best fit line:
y = 832879.19 +  -9975.50x
for Duster
832879.188267 -9975.50184278
before plot 
[ 3.  4.  5.  0.  2.  1.] [ 846557.142

In [13]:
len(new_car_list)

114