In [9]:
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
from matplotlib import style
style.use('ggplot')
import csv 
from statistics import mean 
import glob2 
from sklearn.cluster import KMeans
manufacturers = [] 
new_list = []
with open('car_list.csv', 'rt') as f:
    reader = csv.reader(f)
    for row in reader:
        manufacturers.append(row[0])
manufacturers  = manufacturers[1:]
manufacturers_len = len(set(manufacturers))
print(manufacturers_len)
set_manunfacturers = set(manufacturers)
set_manunfacturers


22


{'Audi',
 'BMW',
 'Chevrolet',
 'Datsun',
 'Fiat',
 'Force Motors',
 'Ford',
 'Honda',
 'Hyundai',
 'Jaguar',
 'Land Rover',
 'Mahindra',
 'Maruti Suzuki',
 'Mercedes-Benz',
 'Mitsubishi',
 'Nissan',
 'Renault',
 'Skoda',
 'Tata',
 'Toyota',
 'Volkswagen',
 'Volvo'}

In [10]:
cars  = []
with open('car_list.csv', 'rt') as f:
    reader = csv.reader(f)
    for row in reader:
        cars.append(row[1])
cars = cars[1:]
import re
count = 0
new_list = []

for m in set_manunfacturers:
    for car in cars:
        if str(m) in str(car):
            count = count+1
            small_list = []
            new_list.append((re.sub(str(m),"",str(car),count=1)).lower())
car_list = []

for list in new_list:
    car_list.append((' '.join(list.split(' ')[1:-1])).capitalize())
path = '/home/saksham/Desktop/majorproject/clustermean/*.csv'       
print(path)
outfile = open('finalfile1.csv', 'w')
writer = csv.writer(outfile)
writer.writerow(['MANUFACTURERE', 'CAR', 'a', 'b'])

/home/saksham/Desktop/majorproject/clustermean/*.csv


23

In [ ]:
for file in glob2.glob(path):
    print(file)
    for car in car_list:
        
        with open(file, 'rt') as f:
            x = []
            y = []
            reader = csv.reader(f)
            for row in reader:
                if row[2] == car:
                    c = car
                    x.append(int(int(row[1]) - 2017))
                    y.append(int(row[3]))
            
            if len(x)>0:
                man = str(file).split('/')[-1]
                print(man)
                man1 = man.split('.')[0]
                print('running')
                nparray = np.empty(shape=[0, 2])
                xs = np.empty(shape=[0,1], dtype=np.float64)
                ys = np.empty(shape=[0,1], dtype=np.float64)
                no_of_clusters = len(set(x))
                for (a, b) in zip(x,y):
                    nparray = np.append(nparray, [[a,b]], axis=0)
                
                kmeans = KMeans(n_clusters=no_of_clusters)
                kmeans.fit(nparray)
                centroids = kmeans.cluster_centers_
                labels = kmeans.labels_
                if no_of_clusters == 8:
                    colors = ["g.", "r.","c.","b.","y.", "w.", "k.", "m."]
                elif no_of_clusters == 7:
                    colors = ["g.", "r.","c.","b.","y.", "w.", "k."]
                elif  no_of_clusters == 6:
                    colors = ["g.", "r.","c.","b.","y.", "w."]
                elif no_of_clusters == 5:
                    colors = ["g.", "r.","c.","b.","y."]
                elif no_of_clusters == 4:
                    colors = ["g.", "r.","c.","b."]
                elif no_of_clusters == 3:
                    colors = ["g.", "r.","c."]
                elif no_of_clusters == 2:
                    colors = ["g.", "r."]
                elif no_of_clusters == 1:
                    colors = ["g."]
                for i in range(len(nparray)):
                    plt.plot(nparray[i][0], nparray[i][1], colors[labels[i]], markersize=10)
                plt.scatter(centroids[:, 0], centroids[:, 1], marker="x", s=150, linewidths=5, zorder=10)
                plt.xlabel("Year")
                plt.ylabel("Price")
                fig1 = plt.gcf()
                plt.draw()
                fig1.savefig('clusteredimage1/' + str(car) + '.png')
                plt.close()
                ym = centroids[:,1]
                xm = centroids[:,0]
                for i in xm:
                    xs = np.append(xs, [[i]])

                for j in ym:
                    ys = np.append(ys, [[j]]) 
                # solve for a and b
                def best_fit(X, Y):

                    xbar = sum(X)/len(X)
                    ybar = sum(Y)/len(Y)
                    n = len(X) # or len(Y)

                    numer = sum(xi*yi for xi,yi in zip(X, Y)) - n * xbar * ybar
                    denum = sum(xi**2 for xi in X) - n * xbar**2

                    b = numer / denum
                    a = ybar - b * xbar

                    print('best fit line:\ny = {:.2f} +  {:.2f}x'.format(a, b))

                    return a, b

                # solution
                a, b = best_fit(xs, ys)
                print('for ' + str(car))
                
                print(a, b)
                print('before plot ')
                print(xs, ys)
                plt.scatter(xs, ys)
                yfit = [a + b * xi for xi in xs]
                plt.plot(xs, yfit)
                plt.xlabel("Year")
                plt.ylabel("Price")
                plt.grid()
                fig1 = plt.gcf()
                plt.draw()
                fig1.savefig('bestfitimage1/' + str(car) + '.png')
                plt.close() 
                
#                 plt.grid()
#                 fig1 = plt.gcf()
#                 plt.draw()
                
#                 fig1.savefig('bestfitimage/' + str(car) + '.png')
                outfile = open('finalfile1.csv', 'a')
                writer = csv.writer(outfile)
                writer.writerow([man1,car,a,b])

/home/saksham/Desktop/majorproject/clustermean/BMW.csv
BMW.csv
running
best fit line:
y = 3179373.43 +  -244625.68x
for X1
3179373.42857 -244625.678571
before plot 
[ 3.  1.  5.  4.  6.  2.  7.] [ 2250000.  3606240.  1606759.  1936375.  1407721.  2400000.  2199000.]
BMW.csv
running
best fit line:
y = 5620004.67 +  -578572.43x
for X3
5620004.66667 -578572.428571
before plot 
[ 2.  5.  1.  3.  6.  4.] [ 4400000.  2762500.  5457507.  3500000.  2500000.  2950000.]
BMW.csv
running
best fit line:
y = 8164186.05 +  -853953.49x
for X5
8164186.04651 -853953.488372
before plot 
[ 3.  6.  7.  2.  5.] [ 5630000.  3400000.  1950000.  6400000.  3800000.]
BMW.csv
running
best fit line:
y = 8486200.80 +  -691193.06x
for Z4
8486200.8 -691193.057143
before plot 
[ 7.  3.  6.  5.] [ 3779749.  6600000.  4450000.  4600000.]
/home/saksham/Desktop/majorproject/clustermean/Renault.csv
Renault.csv
running
best fit line:
y = 359079.00 +  13377.00x
for Kwid
359079.0 13377.0
before plot 
[ 2.  1.] [ 385833.  3724