In [10]:
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
from matplotlib import style
style.use('ggplot')
import csv 
from statistics import mean 
import glob2 
from sklearn.cluster import KMeans
manufacturers = [] 
new_list = []
with open('car_list.csv', 'rt') as f:
    reader = csv.reader(f)
    for row in reader:
        manufacturers.append(row[0])
manufacturers  = manufacturers[1:]
manufacturers_len = len(set(manufacturers))
print(manufacturers_len)
set_manunfacturers = set(manufacturers)
set_manunfacturers


22


{'Audi',
 'BMW',
 'Chevrolet',
 'Datsun',
 'Fiat',
 'Force Motors',
 'Ford',
 'Honda',
 'Hyundai',
 'Jaguar',
 'Land Rover',
 'Mahindra',
 'Maruti Suzuki',
 'Mercedes-Benz',
 'Mitsubishi',
 'Nissan',
 'Renault',
 'Skoda',
 'Tata',
 'Toyota',
 'Volkswagen',
 'Volvo'}

In [11]:
cars  = []
with open('car_list.csv', 'rt') as f:
    reader = csv.reader(f)
    for row in reader:
        cars.append(row[1])
cars = cars[1:]
import re
count = 0
new_list = []

for m in set_manunfacturers:
    for car in cars:
        if str(m) in str(car):
            count = count+1
            small_list = []
            new_list.append((re.sub(str(m),"",str(car),count=1)).lower())
car_list = []

for list in new_list:
    car_list.append((' '.join(list.split(' ')[1:-1])).capitalize())
path = '/home/saksham/Desktop/majorproject/out1/*.csv'       
print(path)
outfile = open('finalfile.csv', 'w')
writer = csv.writer(outfile)
writer.writerow(['MANUFACTURERE', 'CAR', 'a', 'b'])

/home/saksham/Desktop/majorproject/out1/*.csv


23

In [9]:
for file in glob2.glob(path):
    print(file)
    for car in car_list:
        
        with open(file, 'rt') as f:
            x = []
            y = []
            reader = csv.reader(f)
            for row in reader:
                if row[1] == car:
                    c = car
                    x.append(2017-int(row[3])*100000)
                    y.append(int(row[2]))
            
            if len(x)>0:
                man = str(file).split('/')[-1]
                print(man)
                man1 = man.split('.')[0]
                print('running')
                nparray = np.empty(shape=[0, 2])
                xs = np.empty(shape=[0,1], dtype=np.float64)
                ys = np.empty(shape=[0,1], dtype=np.float64)
                no_of_clusters = len(set(x))
                for (a, b) in zip(x,y):
                    nparray = np.append(nparray, [[b,a]], axis=0)
                
                kmeans = KMeans(n_clusters=no_of_clusters)
                kmeans.fit(nparray)
                centroids = kmeans.cluster_centers_
                labels = kmeans.labels_
                if no_of_clusters == 8:
                    colors = ["g.", "r.","c.","b.","y.", "w.", "k.", "m."]
                elif no_of_clusters == 7:
                    colors = ["g.", "r.","c.","b.","y.", "w.", "k."]
                elif  no_of_clusters == 6:
                    colors = ["g.", "r.","c.","b.","y.", "w."]
                elif no_of_clusters == 5:
                    colors = ["g.", "r.","c.","b.","y."]
                elif no_of_clusters == 4:
                    colors = ["g.", "r.","c.","b."]
                elif no_of_clusters == 3:
                    colors = ["g.", "r.","c."]
                elif no_of_clusters == 2:
                    colors = ["g.", "r."]
                elif no_of_clusters == 1:
                    colors = ["g."]
                for i in range(len(nparray)):
                    plt.plot(nparray[i][0], nparray[i][1], colors[labels[i]], markersize=10)
                plt.scatter(centroids[:, 0], centroids[:, 1], marker="x", s=150, linewidths=5, zorder=10)
                plt.xlabel("Year")
                plt.ylabel("Price")
                fig1 = plt.gcf()
                plt.draw()
                fig1.savefig('clusteredimage/' + str(car) + '1.png')
                plt.close()
                ym = centroids[:,1]
                print(xm)
                xm = centroids[:,0]
                for i in xm:
                    xs = np.append(xs, [[int(i)/100000]])

                for j in ym:
                    ys = np.append(ys, [[j]]) 
                # solve for a and b
                def best_fit(X, Y):

                    xbar = sum(X)/len(X)
                    ybar = sum(Y)/len(Y)
                    n = len(X) # or len(Y)

                    numer = sum(xi*yi for xi,yi in zip(X, Y)) - n * xbar * ybar
                    denum = sum(xi**2 for xi in X) - n * xbar**2

                    b = numer / denum
                    a = ybar - b * xbar

                    print('best fit line:\ny = {:.2f} +  {:.2f}x'.format(a, b))

                    return a, b

                # solution
                a, b = best_fit(xs, ys)
                print('for ' + str(car))
                
                print(a, b)
                print('before plot ')
                print(xs, ys)
                plt.scatter(xs, ys)
                yfit = [a + b * xi for xi in xs]
                plt.plot(xs, yfit)
                plt.xlabel("Year")
                plt.ylabel("Price")
                plt.grid()
                fig1 = plt.gcf()
                plt.draw()
                fig1.savefig('bestfitimage/' + str(car) + '1.png')
                plt.close() 
                
#                 plt.grid()
#                 fig1 = plt.gcf()
#                 plt.draw()
                
#                 fig1.savefig('bestfitimage/' + str(car) + '.png')
                outfile = open('finalfile.csv', 'a')
                writer = csv.writer(outfile)
                writer.writerow([man1,car,a,b])

/home/saksham/Desktop/majorproject/out1/BMW.csv
BMW.csv
running
[ 1070555.55555556   643761.83333333   583500.6097561   1800000.
   727361.08333333  1468750.           848884.61538462]
best fit line:
y = -200818411.51 +  -22474.90x
for X1
-200818411.508 -22474.9008041
before plot 
[ 15.1234   32.5      21.55     18.1      13.45908  37.       24.16666] [ -2.01151316e+08  -2.01597983e+08  -2.01222983e+08  -2.01267983e+08
  -2.01097983e+08  -2.01597983e+08  -2.01431316e+08]
BMW.csv
running
[ 1512340.66666667  3250000.          2155000.          1810000.1
  1345908.63636364  3700000.          2416666.66666667]
best fit line:
y = -200708557.75 +  -18560.22x
for X3
-200708557.75 -18560.2180802
before plot 
[ 28.29166  46.5      25.       35.       42.       29.91666] [ -2.01214650e+08  -2.01547983e+08  -2.01164650e+08  -2.01397983e+08
  -2.01497983e+08  -2.01264650e+08]
BMW.csv
running
[ 2829166.66666667  4650000.          2500000.          3500000.          4200000.
  2991666.66666667]
best

/usr/local/lib/python3.5/dist-packages/ipykernel/__main__.py:74: RuntimeWarning: invalid value encountered in double_scalars


/home/saksham/Desktop/majorproject/out1/Renault.csv
Renault.csv
running
[ 4250000.]
best fit line:
y = -194030729.28 +  -1935359.01x
for Kwid
-194030729.275 -1935359.00892
before plot 
[ 3.85833  3.91   ] [ -2.01497983e+08  -2.01597983e+08]
Renault.csv
running
[ 385833.33333333  391000.        ]
best fit line:
y = -200790898.16 +  -109605.99x
for Pulse
-200790898.16 -109605.988756
before plot 
[ 5.       3.54166  6.25   ] [ -2.01297983e+08  -2.01197983e+08  -2.01497983e+08]
Renault.csv
running
[ 500000.          354166.33333333  625000.        ]
best fit line:
y = -200991014.03 +  -45187.13x
for Scala
-200991014.027 -45187.1295826
before plot 
[ 6.525  5.626  4.95   6.31 ] [ -2.01347983e+08  -2.01297983e+08  -2.01197983e+08  -2.01177983e+08]
Renault.csv
running
[ 652500.  562600.  495000.  631000.]
best fit line:
y = -201724097.95 +  19108.31x
for Lodgy
-201724097.946 19108.3106822
before plot 
[  9.74     11.83333] [ -2.01537983e+08  -2.01497983e+08]
Renault.csv
running
[  974000.    